const fs=require('node:fs');const {PHCore:c,PH_COMMANDS:commands,PH_TEMPLATES:templates,PHCatalog:k}=require('./load-core');
const cases=[];
for(const d of commands){const n=c.makeNode(d.id);const before=[];for(const key of d.uses||[])before.push(c.makeNode('variable',{value:'@()'},n.values[key]));if(d.container)n.children=[c.makeNode('message')];cases.push({name:d.id,code:c.compile({steps:[...before,n],settings:{style:'detailed',preview:true,comments:true}}).code,command:d.kind?null:d.command,parameters:d.kind?[]:d.fields.filter(f=>f.key!==d.inputField).map(f=>f.key)});}
for(const t of templates)cases.push({name:t.id,code:c.compile({steps:t.steps.map(s=>c.makeNode(s.def,s.values,s.out,s.children)),settings:{style:'detailed',preview:true,comments:true}}).code});
for(const d of k.entries){for(const set of d.metadata.sets){const n=c.makeNode(d.id,{_set:set.name,_effect:'Nur lesen'});for(const sp of set.parameters){const param=d.metadata.parameters.find(p=>p.name===sp.name);if(!param)continue;const f=d.fields.find(f=>f.key===sp.name);n.values[sp.name]=f.type==='bool'?true:param.validateSet.length?param.validateSet[0]:/ScriptBlock/.test(param.type)?{expr:'{ $_ }'}:/Hashtable/.test(param.type)?{expr:'@{ Name = \"Test\" }'}:/PSCredential/.test(param.type)?{expr:'$Credential'}:/SecureString/.test(param.type)?{expr:'$Password'}:/CimInstance|PSObject|Object\[\]|System.Type/.test(param.type)?{expr:'$Object'}:/System\.(?:S?Byte|U?Int(?:16|32|64)|Single|Double|Decimal)/.test(param.type)?'1':param.type==='System.Boolean'?'True':"O'Brien";}cases.push({name:d.id+'/'+set.name,code:c.compile({steps:[n],settings:{style:'detailed',preview:true,comments:true}}).code,command:d.command,parameters:set.parameters.map(p=>p.name)});}}
for(const d of commands){const n=c.makeNode(d.id),before=[];for(const key of d.uses||[])before.push(c.makeNode('variable',{value:'@()'},n.values[key]));if(d.container)n.children=[c.makeNode('message')];for(const preview of [false,true])cases.push({name:'compact/'+d.id+'/'+preview,code:c.compile({steps:[...before,n],settings:{style:'simple',preview,comments:false}}).code});}
for(const t of templates)cases.push({name:'compact/'+t.id,code:c.compile({steps:t.steps.map(s=>c.makeNode(s.def,s.values,s.out,s.children)),settings:{style:'simple',preview:false,comments:false}}).code});
fs.writeFileSync(process.argv[2]||'cases.json',JSON.stringify(cases,null,2),'utf8');
console.log(`Generated ${cases.length} parser test cases`);
