/* PowerHelp 2: curated Windows PowerShell 5.1 building blocks.
 * Parameters carry types. Text is always emitted as a single-quoted literal.
 * Expressions are deliberately separate and remain visible as code.
 */
const PH_VERSION = '2.0.0';
const PH_CATEGORIES = ['Dateien & Ordner','Text & Regex','CSV & Daten','Benutzer & Gruppen','Berechtigungen & Freigaben','Dienste & Prozesse','Netzwerk','System & Ereignisse','Aufgabenplanung','Active Directory','Skriptlogik'];
const F = (key,label,type='text',value='',extra={})=>({key,label,type,value,...extra});
const S = (key,label,value='',extra={})=>F(key,label,'text',value,extra);
const E = (key,label,value='',extra={})=>F(key,label,'expr',value,extra);
const V = (key,label,value='Daten',extra={})=>F(key,label,'var',value,extra);
const B = (key,label,value=false,extra={})=>F(key,label,'bool',value,extra);
const N = (key,label,value=10,extra={})=>F(key,label,'number',value,extra);
const C = (key,label,options,value=options[0],extra={})=>F(key,label,'enum',value,{options,...extra});
const OPT = {optional:true};
const PH_COMMANDS = [];
function cmd(id,title,category,command,description,fields=[],extra={}) {
  PH_COMMANDS.push({id,title,category,command,description,fields,keywords:'',...extra});
}
const P = 'Dateien & Ordner', T = 'Text & Regex', D = 'CSV & Daten', U = 'Benutzer & Gruppen', A = 'Berechtigungen & Freigaben', SV = 'Dienste & Prozesse', NET = 'Netzwerk', SYS = 'System & Ereignisse', TASK = 'Aufgabenplanung', AD = 'Active Directory', LOGIC = 'Skriptlogik';
cmd('files','Dateien und Ordner suchen',P,'Get-ChildItem','Sucht nach Dateimustern; optional auch in Unterordnern.',[S('LiteralPath','Suchordner','C:\\Daten'),S('Filter','Dateimuster','*.txt'),B('Recurse','Unterordner durchsuchen'),B('File','Nur Dateien',true),B('Directory','Nur Ordner'),B('Force','Versteckte Elemente einbeziehen')],{out:'Dateien',keywords:'finden suchen auflisten rekursiv verzeichnis dir gci ls dateiliste'});
cmd('mkdir','Ordner anlegen',P,'New-Item','Erstellt ein Verzeichnis. Mit Force darf es bereits existieren.',[S('Path','Ordnerpfad','C:\\Daten\\Export'),C('ItemType','Elementtyp',['Directory'],'Directory'),B('Force','Vorhandenen Ordner akzeptieren',true)],{mutates:true,keywords:'erstellen verzeichnis neu mkdir'});
cmd('copy','Dateien oder Ordner kopieren',P,'Copy-Item','Kopiert einen konkreten Pfad. Für viele Dateien: Suchschritt und Schleife verwenden.',[S('LiteralPath','Quelle','C:\\Daten\\Bericht.txt'),S('Destination','Ziel','C:\\Archiv\\Bericht.txt'),B('Recurse','Unterordner mitkopieren'),B('Force','Schreibschutz überschreiben')],{mutates:true,keywords:'backup sichern kopieren copy cp'});
cmd('move','Dateien oder Ordner verschieben',P,'Move-Item','Verschiebt Dateien oder Verzeichnisse an den Zielpfad.',[S('LiteralPath','Quelle','C:\\Daten\\Bericht.txt'),S('Destination','Ziel','C:\\Archiv\\Bericht.txt'),B('Force','Ersetzen erzwingen')],{mutates:true,keywords:'verschieben umziehen archivieren mv'});
cmd('rename','Datei oder Ordner umbenennen',P,'Rename-Item','NewName ist der neue Name, kein anderer Zielordner.',[S('LiteralPath','Vorhandener Pfad','C:\\Daten\\alt.txt'),S('NewName','Neuer Name','neu.txt')],{mutates:true,keywords:'rename umbenennen name ändern'});
cmd('remove','Datei oder Ordner entfernen',P,'Remove-Item','Entfernt den angegebenen Pfad; keine Papierkorb-Funktion.',[S('LiteralPath','Zu entfernender Pfad','C:\\Temp\\alt.txt'),B('Recurse','Inhalt von Ordnern mitentfernen'),B('Force','Versteckte/geschützte Elemente entfernen')],{mutates:true,risk:'Löscht dauerhaft.',keywords:'löschen entfernen aufräumen delete rm bereinigen'});
cmd('exists','Pfad auf Existenz prüfen',P,'Test-Path','Liefert True oder False. Kann als Bedingung verwendet werden.',[S('LiteralPath','Pfad','C:\\Daten'),C('PathType','Gesuchter Typ',['Any','Container','Leaf'])],{out:'PfadExistiert',keywords:'existiert vorhanden prüfen test'});
cmd('item','Dateieigenschaften lesen',P,'Get-Item','Liest das Objekt zu einem einzelnen Pfad.',[S('LiteralPath','Pfad','C:\\Daten\\Bericht.txt')],{out:'Datei',keywords:'größe eigenschaften datum details metadata'});
cmd('hash','Datei-Prüfsumme berechnen',P,'Get-FileHash','Berechnet einen Hash, um Dateien zu vergleichen oder Integrität zu prüfen.',[S('LiteralPath','Datei','C:\\Daten\\Bericht.txt'),C('Algorithm','Hash-Verfahren',['SHA256','SHA512','SHA1','MD5'])],{out:'Pruefsumme',keywords:'checksum hash doppelte duplikate integrität sha256'});
cmd('zip','ZIP-Archiv erstellen',P,'Compress-Archive','Komprimiert Dateien oder Ordner; Archive über 2 GB und versteckte Dateien haben Einschränkungen.',[S('LiteralPath','Quelle','C:\\Daten'),S('DestinationPath','ZIP-Datei','C:\\Backup\\Daten.zip'),B('Force','Archiv ersetzen')],{mutates:true,keywords:'zip komprimieren packen backup archiv'});
cmd('unzip','ZIP-Archiv entpacken',P,'Expand-Archive','Entpackt ein ZIP-Archiv in einen Ordner.',[S('LiteralPath','ZIP-Datei','C:\\Backup\\Daten.zip'),S('DestinationPath','Zielordner','C:\\Restore'),B('Force','Dateien ersetzen')],{mutates:true,keywords:'zip entpacken wiederherstellen unzip'});
cmd('joinpath','Pfadteile verbinden',P,'Join-Path','Verbindet einen Basisordner und einen Unterpfad.',[S('Path','Basisordner','C:\\Daten'),S('ChildPath','Unterpfad','Export\\liste.csv')],{out:'Zielpfad',keywords:'pfad zusammenbauen kombinieren'});
cmd('robocopy','Ordner robust sichern',P,'robocopy','Kopiert mit Wiederholungen, erhält Daten/Attribute/Zeitstempel. Exitcodes ab 8 werden als Fehler behandelt.',[S('source','Quellordner','C:\\Daten'),S('target','Zielordner','D:\\Backup'),B('recurse','Unterordner einschließen',true),B('mirror','Ziel spiegeln (löscht zusätzliche Zieldateien)'),N('retries','Wiederholungen',2),N('wait','Wartezeit in Sekunden',3)],{kind:'robocopy',mutates:true,keywords:'robocopy backup spiegeln synchronisieren sicherung mirror'});
cmd('read','Textdatei lesen',T,'Get-Content','Liest eine Datei als Zeilen oder als gesamten Text.',[S('LiteralPath','Dateipfad','C:\\Daten\\bericht.txt'),B('Raw','Gesamte Datei als ein Text',true),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8')],{out:'Text',keywords:'lesen inhalt text laden zeilen cat gc'});
cmd('write','Textdatei schreiben',T,'Set-Content','Ersetzt den Dateiinhalt durch den angegebenen Wert.',[S('LiteralPath','Dateipfad','C:\\Daten\\ergebnis.txt'),S('Value','Text','Beispieltext'),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8')],{mutates:true,keywords:'schreiben speichern text ausgabe überschreiben'});
cmd('append','Text an Datei anhängen',T,'Add-Content','Fügt Text am Ende einer Datei hinzu.',[S('LiteralPath','Dateipfad','C:\\Daten\\protokoll.txt'),S('Value','Text','Eintrag'),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8')],{mutates:true,keywords:'anhängen append protokoll log'});
cmd('selectstring','Text in Dateien finden',T,'Select-String','Sucht mit Regex; die Ausgabe enthält unter anderem Dateiname und Zeilennummer.',[S('LiteralPath','Dateipfad','C:\\Daten\\bericht.txt'),S('Pattern','Regex / Suchtext','Fehler|Error'),B('SimpleMatch','Als wörtlichen Text suchen'),B('CaseSensitive','Groß-/Kleinschreibung beachten'),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8')],{out:'Texttreffer',keywords:'grep suchen regex match zeile fehler auswerten'});
cmd('regex','Daten mit Regex extrahieren',T,'[regex]::Matches','Sammelt Treffer aus mehreren Textdateien und liest eine benannte oder nummerierte Gruppe aus.',[S('folder','Suchordner','C:\\Daten'),S('filter','Dateimuster','*.txt'),S('pattern','Regulärer Ausdruck','(?m)^Kundennummer:\\s*(?<wert>\\S+)'),S('group','Treffergruppe (0 = gesamter Treffer)','wert'),C('encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8'),B('recurse','Unterordner durchsuchen')],{kind:'regex',out:'Treffer',keywords:'extrahieren auslesen id kundennummer email datum regulärer ausdruck capture gruppen daten'});
cmd('replace','Text mit Regex ersetzen',T,'-replace','Ersetzt in einer vorhandenen Textvariablen. Rückverweise wie $1 werden als Text eingetragen.',[V('input','Textvariable','Text'),S('pattern','Regex','\\s+'),S('replacement','Ersetzung',' ',{allowEmpty:true})],{kind:'replace',out:'BereinigterText',uses:['input'],keywords:'replace ersetzen bereinigen austauschen regex'});
cmd('split','Text aufteilen',T,'-split','Teilt eine Textvariable anhand eines Regex-Trenners auf.',[V('input','Textvariable','Text'),S('pattern','Trenner als Regex',';')],{kind:'split',out:'Teile',uses:['input'],keywords:'split trennen aufteilen zerlegen'});
cmd('csvin','CSV-Datei einlesen',D,'Import-Csv','Liest Tabellenzeilen als Objekte für Schleifen und Filter.',[S('LiteralPath','CSV-Datei','C:\\Daten\\import.csv'),C('Delimiter','Trennzeichen',[';',',','TAB'],';'),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8')],{out:'Datensaetze',keywords:'csv import einlesen excel tabelle massenimport'});
cmd('csvout','Daten als CSV exportieren',D,'Export-Csv','Exportiert eine vorhandene Variable. Erst am Ende formatieren, nicht vor diesem Export.',[V('input','Datenvariable','Treffer'),S('LiteralPath','CSV-Zieldatei','C:\\Daten\\Export\\ergebnis.csv'),C('Delimiter','Trennzeichen',[';',',','TAB'],';'),C('Encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'UTF8'),B('NoTypeInformation','Typzeile weglassen',true)],{inputField:'input',uses:['input'],mutates:true,keywords:'csv export ausgabe speichern excel tabelle'});
cmd('jsonin','JSON-Text einlesen',D,'ConvertFrom-Json','Wandelt eine Textvariable in PowerShell-Objekte um.',[V('input','JSON-Textvariable','Text')],{inputField:'input',uses:['input'],out:'JsonDaten',keywords:'json import parsen objekt'});
cmd('jsonout','Daten in JSON umwandeln',D,'ConvertTo-Json','Wandelt eine Datenvariable in JSON-Text um.',[V('input','Datenvariable','Datensaetze'),N('Depth','Maximale Tiefe',10,{min:1,max:100})],{inputField:'input',uses:['input'],out:'JsonText',keywords:'json export serialisieren'});
cmd('where','Daten filtern',D,'Where-Object','Filtert mit einem sichtbaren PowerShell-Ausdruck. $_ ist das aktuelle Objekt.',[V('input','Datenvariable','Dateien'),E('condition','Filterausdruck',"$_.Length -gt 1MB")],{kind:'where',uses:['input'],out:'Auswahl',keywords:'filtern where bedingung älter größer enabled auswählen'});
cmd('sort','Daten sortieren',D,'Sort-Object','Sortiert nach einer oder mehreren Eigenschaften.',[V('input','Datenvariable','Dateien'),F('Property','Eigenschaften (Komma getrennt)','list','LastWriteTime'),B('Descending','Absteigend sortieren'),B('Unique','Doppelte Werte entfernen')],{inputField:'input',uses:['input'],out:'SortierteDaten',keywords:'sortieren reihenfolge unique duplikate doppelte'});
cmd('select','Eigenschaften auswählen',D,'Select-Object','Wählt Eigenschaften für Berichte und Exporte aus.',[V('input','Datenvariable','Dateien'),F('Property','Eigenschaften (Komma getrennt)','list','Name, FullName, Length, LastWriteTime')],{inputField:'input',uses:['input'],out:'Bericht',keywords:'select eigenschaften spalten auswählen bericht'});
cmd('measure','Anzahl und Summen berechnen',D,'Measure-Object','Berechnet Anzahl und optional Summe oder Durchschnitt einer Eigenschaft.',[V('input','Datenvariable','Dateien'),S('Property','Eigenschaft','Length',OPT),B('Sum','Summe bilden',true),B('Average','Durchschnitt bilden')],{inputField:'input',uses:['input'],out:'Statistik',keywords:'zählen summe anzahl statistik größe durchschnitt'});
cmd('group','Daten gruppieren',D,'Group-Object','Gruppiert Objekte nach einer Eigenschaft.',[V('input','Datenvariable','Dateien'),S('Property','Eigenschaft','Extension')],{inputField:'input',uses:['input'],out:'GruppierteDaten',keywords:'gruppieren zusammenfassen group count'});
cmd('compare','Zwei Datenlisten vergleichen',D,'Compare-Object','Zeigt Unterschiede zwischen zwei Variablen.',[V('ReferenceObject','Referenzliste','Alt'),V('DifferenceObject','Vergleichsliste','Neu'),F('Property','Eigenschaften','list','Name',OPT)],{out:'Unterschiede',uses:['ReferenceObject','DifferenceObject'],keywords:'vergleichen unterschied compare diff listen'});
cmd('table','Daten als Tabelle anzeigen',D,'Format-Table','Nur für die Anzeige verwenden. Die Ausgabe ist kein Datensatz für CSV-Exporte.',[V('input','Datenvariable','Dateien'),F('Property','Eigenschaften','list','Name, Length',OPT),B('AutoSize','Spaltenbreite anpassen',true)],{inputField:'input',uses:['input'],keywords:'tabelle anzeigen ausgabe formatieren'});
cmd('users','Lokale Benutzer auflisten',U,'Get-LocalUser','Liest lokale Benutzer des ausführenden Rechners.',[S('Name','Benutzername (leer = alle)','',OPT)],{out:'Benutzer',module:'Microsoft.PowerShell.LocalAccounts',keywords:'benutzer konten user lokal auflisten anzeigen'});
cmd('newuser','Lokalen Benutzer anlegen',U,'New-LocalUser','Das Kennwort wird erst bei der Skriptausführung verdeckt abgefragt.',[S('Name','Benutzername','Max'),S('FullName','Vollständiger Name','Max Beispiel'),S('Description','Beschreibung','Projektkonto',OPT),B('PasswordNeverExpires','Kennwort läuft nie ab')],{kind:'newuser',module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'benutzer konto erstellen neu kennwort passwort'});
cmd('setuser','Lokalen Benutzer ändern',U,'Set-LocalUser','Ändert Name/Beschreibung eines bestehenden Kontos.',[S('Name','Benutzername','Max'),S('FullName','Vollständiger Name','Max Beispiel'),S('Description','Beschreibung','Projektkonto',OPT)],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'user benutzer ändern beschreibung'});
cmd('enableuser','Lokalen Benutzer aktivieren',U,'Enable-LocalUser','Aktiviert ein vorhandenes lokales Konto.',[S('Name','Benutzername','Max')],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'user benutzer konto aktivieren entsperren'});
cmd('disableuser','Lokalen Benutzer deaktivieren',U,'Disable-LocalUser','Deaktiviert ein vorhandenes lokales Konto.',[S('Name','Benutzername','Max')],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'user benutzer konto deaktivieren sperren'});
cmd('deluser','Lokalen Benutzer entfernen',U,'Remove-LocalUser','Entfernt das lokale Konto. Profildaten werden damit nicht automatisch bereinigt.',[S('Name','Benutzername','Max')],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,risk:'Entfernt ein Benutzerkonto.',keywords:'user benutzer löschen entfernen'});
cmd('groups','Lokale Gruppen auflisten',U,'Get-LocalGroup','Liest lokale Gruppen des ausführenden Rechners.',[S('Name','Gruppenname (leer = alle)','',OPT)],{out:'Gruppen',module:'Microsoft.PowerShell.LocalAccounts',keywords:'gruppen anzeigen auflisten lokal'});
cmd('newgroup','Lokale Gruppe anlegen',U,'New-LocalGroup','Erstellt eine lokale Sicherheitsgruppe.',[S('Name','Gruppenname','Projektteam'),S('Description','Beschreibung','Projektmitglieder',OPT)],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'gruppe erstellen anlegen neu'});
cmd('members','Gruppenmitglieder auflisten',U,'Get-LocalGroupMember','Liest die Mitglieder einer lokalen Gruppe.',[S('Group','Gruppenname','Projektteam')],{out:'Mitglieder',module:'Microsoft.PowerShell.LocalAccounts',keywords:'mitgliedschaft mitglieder gruppe prüfen'});
cmd('addmember','Mitglied zur lokalen Gruppe hinzufügen',U,'Add-LocalGroupMember','Fügt ein lokales Konto oder DOMÄNE\\Konto hinzu.',[S('Group','Gruppenname','Projektteam'),S('Member','Benutzer / DOMÄNE\\Konto','Max')],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'gruppe mitglied hinzufügen berechtigung'});
cmd('delmember','Mitglied aus lokaler Gruppe entfernen',U,'Remove-LocalGroupMember','Entfernt eine lokale Gruppenmitgliedschaft.',[S('Group','Gruppenname','Projektteam'),S('Member','Benutzer / DOMÄNE\\Konto','Max')],{module:'Microsoft.PowerShell.LocalAccounts',mutates:true,keywords:'gruppe mitglied entfernen entziehen'});
cmd('acl','NTFS-Berechtigungen lesen',A,'Get-Acl','Liest den Sicherheitsdeskriptor eines Pfads.',[S('LiteralPath','Datei oder Ordner','C:\\Daten')],{out:'Acl',keywords:'ntfs rechte berechtigungen acl lesen zugriff'});
cmd('grant','NTFS-Berechtigung hinzufügen',A,'Get-Acl / Set-Acl','Ergänzt eine Zugriffsregel und erhält bestehende Regeln. Vererbung wird separat ausgewählt.',[S('path','Ordnerpfad','C:\\Daten'),S('identity','Benutzer oder Gruppe','Projektteam'),C('rights','Berechtigung',['ReadAndExecute','Modify','FullControl','Read','Write'],'Modify'),B('inherit','Für Unterordner und Dateien vererben',true)],{kind:'aclgrant',mutates:true,keywords:'ntfs rechte zugriff erlauben berechtigen modify vollzugriff ordner'});
cmd('shares','SMB-Freigaben auflisten',A,'Get-SmbShare','Zeigt Freigaben auf dem ausführenden Rechner.',[S('Name','Freigabename (leer = alle)','',OPT)],{out:'Freigaben',module:'SmbShare',keywords:'smb share freigabe anzeigen netzlaufwerk'});
cmd('newshare','SMB-Freigabe erstellen',A,'New-SmbShare','Erstellt eine Freigabe. NTFS-Rechte müssen zusätzlich passend gesetzt werden.',[S('Name','Freigabename','Projekt'),S('Path','Freigegebener Ordner','C:\\Daten\\Projekt'),S('ChangeAccess','Gruppe mit Änderungsrechten','Projektteam')],{module:'SmbShare',mutates:true,keywords:'smb freigabe erstellen share netzwerkordner'});
cmd('shareaccess','Freigaberechte lesen',A,'Get-SmbShareAccess','Zeigt die Freigabeberechtigungen einer SMB-Freigabe.',[S('Name','Freigabename','Projekt')],{out:'Freigaberechte',module:'SmbShare',keywords:'freigabe berechtigungen rechte smb lesen'});
cmd('grantshare','Freigaberechte erteilen',A,'Grant-SmbShareAccess','Erteilt einer Identität Freigaberechte.',[S('Name','Freigabename','Projekt'),S('AccountName','Benutzer / Gruppe','Projektteam'),C('AccessRight','Recht',['Read','Change','Full'],'Change')],{module:'SmbShare',mutates:true,keywords:'freigabe rechte erlauben berechtigung smb'});
cmd('services','Dienste auflisten',SV,'Get-Service','Liest Windows-Dienste anhand des Dienstnamens oder Musters.',[S('Name','Dienstname / Muster','*')],{out:'Dienste',keywords:'dienst service status anzeigen auflisten'});
for (const [id,title,command,keys] of [['startservice','Dienst starten','Start-Service','start starten'],['stopservice','Dienst stoppen','Stop-Service','stop stoppen beenden'],['restartservice','Dienst neu starten','Restart-Service','restart neustart starten']]) cmd(id,title,SV,command,'Verwendet den internen Dienstnamen, nicht den Anzeigenamen.',[S('Name','Dienstname','Spooler')],{mutates:true,keywords:`dienst service ${keys}`});
cmd('setservice','Dienst-Starttyp ändern',SV,'Set-Service','Ändert den Starttyp eines Dienstes.',[S('Name','Dienstname','Spooler'),C('StartupType','Starttyp',['Automatic','Manual','Disabled'],'Automatic')],{mutates:true,keywords:'dienst service autostart starttyp deaktivieren automatisch'});
cmd('processes','Prozesse auflisten',SV,'Get-Process','Liest laufende Prozesse anhand ihres Namens.',[S('Name','Prozessname / Muster','*')],{out:'Prozesse',keywords:'prozess task cpu ram speicher taskmanager'});
cmd('stopprocess','Prozess beenden',SV,'Stop-Process','Beendet Prozesse anhand ihres Namens.',[S('Name','Prozessname','notepad'),B('Force','Beenden erzwingen')],{mutates:true,risk:'Nicht gespeicherte Daten können verloren gehen.',keywords:'prozess kill beenden stoppen'});
cmd('startprocess','Programm starten',SV,'Start-Process','Startet ein Programm mit optionalen Argumenten.',[S('FilePath','Programm','notepad.exe'),S('ArgumentList','Argumente','',OPT),B('Wait','Auf Programmende warten')],{mutates:true,keywords:'programm starten ausführen exe prozess'});
cmd('ping','Erreichbarkeit prüfen',NET,'Test-Connection','Prüft ICMP-Erreichbarkeit. Ein gesperrtes ICMP ist kein Beweis für einen ausgefallenen Host.',[S('ComputerName','Rechner / IP','server01'),N('Count','Anzahl Anfragen',2,{min:1,max:100}),B('Quiet','Nur True/False ausgeben',true)],{out:'Erreichbar',keywords:'ping erreichbarkeit online offline verbindung host'});
cmd('port','TCP-Port prüfen',NET,'Test-NetConnection','Prüft eine TCP-Verbindung auf einem bestimmten Port.',[S('ComputerName','Rechner / IP','server01'),N('Port','TCP-Port',445,{min:1,max:65535})],{out:'Porttest',module:'NetTCPIP',keywords:'tcp port firewall verbindung prüfen 445 3389 rdp smb'});
cmd('dns','DNS-Namen auflösen',NET,'Resolve-DnsName','Fragt DNS-Einträge ab.',[S('Name','DNS-Name','server01.example.local'),C('Type','Eintragstyp',['A','AAAA','MX','TXT','CNAME','PTR'],'A'),S('Server','DNS-Server (optional)','',OPT)],{out:'DnsAntwort',module:'DnsClient',keywords:'dns ip auflösen nslookup name adresse'});
cmd('ip','IP-Adressen anzeigen',NET,'Get-NetIPAddress','Liest IP-Adressen der Netzwerkadapter.',[C('AddressFamily','Adressfamilie',['IPv4','IPv6'],'IPv4')],{out:'IPAdressen',module:'NetTCPIP',keywords:'ip adresse netzwerk interface adapter ipconfig'});
cmd('adapters','Netzwerkadapter anzeigen',NET,'Get-NetAdapter','Liest Status und Eigenschaften der Adapter.',[S('Name','Adaptername / Muster','*')],{out:'Adapter',module:'NetAdapter',keywords:'netzwerk karte adapter mac status'});
cmd('connections','TCP-Verbindungen anzeigen',NET,'Get-NetTCPConnection','Zeigt bestehende TCP-Verbindungen und Listener.',[],{out:'Verbindungen',module:'NetTCPIP',keywords:'netstat tcp verbindung listening port'});
cmd('firewall','Firewall-Regeln anzeigen',NET,'Get-NetFirewallRule','Liest Regeln anhand ihres Anzeigenamens.',[S('DisplayName','Anzeigename / Muster','*')],{out:'FirewallRegeln',module:'NetSecurity',keywords:'firewall regeln anzeigen port sperre'});
cmd('firewallnew','Eingehenden TCP-Port erlauben',NET,'New-NetFirewallRule','Erstellt eine eingehende TCP-Regel mit dem gewählten Port.',[S('DisplayName','Regelname','Projekt TCP'),C('Direction','Richtung',['Inbound'],'Inbound'),C('Action','Aktion',['Allow'],'Allow'),C('Protocol','Protokoll',['TCP'],'TCP'),N('LocalPort','Lokaler Port',8443,{min:1,max:65535}),C('Profile','Netzwerkprofil',['Domain','Private','Any'],'Domain')],{mutates:true,module:'NetSecurity',keywords:'firewall öffnen port freigeben tcp inbound'});
cmd('cim','Systeminformationen abfragen',SYS,'Get-CimInstance','Liest eine Windows-CIM-Klasse, zum Beispiel Betriebssystem, Datenträger oder Hardware.',[C('ClassName','Klasse',['Win32_OperatingSystem','Win32_ComputerSystem','Win32_LogicalDisk','Win32_BIOS','Win32_Processor','Win32_PhysicalMemory','Win32_Service'],'Win32_OperatingSystem'),S('ComputerName','Rechner (leer = lokal)','',OPT)],{out:'Systemdaten',keywords:'system hardware inventar betriebssystem ram disk platte speicher wmi cim'});
cmd('events','Ereignisprotokoll lesen',SYS,'Get-WinEvent','Liest die neuesten Ereignisse eines Windows-Protokolls.',[C('LogName','Protokoll',['System','Application','Security'],'System'),N('MaxEvents','Maximale Anzahl',100,{min:1,max:100000})],{out:'Ereignisse',keywords:'eventlog ereignisse fehler warnung log protokoll security'});
cmd('hotfix','Windows-Updates anzeigen',SYS,'Get-HotFix','Liest installierte Hotfixes; die Liste bildet nicht jeden Update-Typ ab.',[],{out:'Updates',keywords:'updates hotfix patch kb windows installiert'});
cmd('volumes','Laufwerke und freien Platz lesen',SYS,'Get-Volume','Liest Volumes mit Größe und freiem Speicher.',[],{out:'Volumes',module:'Storage',keywords:'platte laufwerk volume speicher frei voll kapazität disk'});
cmd('disks','Physische Datenträger lesen',SYS,'Get-Disk','Liest angeschlossene Datenträger; verändert keine Partitionen.',[],{out:'Datentraeger',module:'Storage',keywords:'disk datenträger platte ssd hdd partition'});
cmd('regread','Registry-Werte lesen',SYS,'Get-ItemProperty','Liest Werte eines Registry-Schlüssels.',[S('LiteralPath','Registry-Pfad','HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion')],{out:'RegistryWerte',keywords:'registry regedit schlüssel lesen'});
cmd('regwrite','Registry-Wert setzen',SYS,'New-ItemProperty','Erstellt oder ersetzt einen Wert in einem vorhandenen Registry-Schlüssel.',[S('LiteralPath','Registry-Pfad','HKCU:\\Software\\PowerHelp'),S('Name','Wertname','Beispiel'),C('PropertyType','Werttyp',['String','ExpandString','DWord','QWord'],'String'),S('Value','Wert','1'),B('Force','Wert ersetzen',true)],{mutates:true,keywords:'registry wert schreiben setzen dword string regedit'});
cmd('tasks','Geplante Aufgaben auflisten',TASK,'Get-ScheduledTask','Liest Aufgaben aus der Windows-Aufgabenplanung.',[S('TaskName','Aufgabenname / Muster','*')],{out:'Aufgaben',module:'ScheduledTasks',keywords:'task scheduler aufgabenplanung zeitplan geplante aufgaben'});
cmd('taskinfo','Letzte Ausführung einer Aufgabe lesen',TASK,'Get-ScheduledTaskInfo','Zeigt Laufzeit und Ergebnis einer geplanten Aufgabe.',[S('TaskName','Aufgabenname','PowerHelp-Backup')],{out:'Aufgabenstatus',module:'ScheduledTasks',keywords:'task aufgabe ergebnis status letzte ausführung'});
cmd('tasknew','Tägliche PowerShell-Aufgabe erstellen',TASK,'Register-ScheduledTask','Registriert eine tägliche Aufgabe für das aktuell angemeldete Konto (interaktive Anmeldung).', [S('name','Aufgabenname','PowerHelp-Backup'),S('script','Skriptpfad','C:\\Skripte\\Backup.ps1'),S('time','Uhrzeit (HH:mm)','18:00')],{kind:'tasknew',module:'ScheduledTasks',mutates:true,keywords:'task aufgabe erstellen täglich automatisch zeitplan scheduler'});
cmd('taskstart','Geplante Aufgabe starten',TASK,'Start-ScheduledTask','Startet eine vorhandene Aufgabe.',[S('TaskName','Aufgabenname','PowerHelp-Backup')],{module:'ScheduledTasks',mutates:true,keywords:'task aufgabe starten ausführen'});
cmd('taskdisable','Geplante Aufgabe deaktivieren',TASK,'Disable-ScheduledTask','Deaktiviert eine vorhandene Aufgabe.',[S('TaskName','Aufgabenname','PowerHelp-Backup')],{module:'ScheduledTasks',mutates:true,keywords:'task aufgabe deaktivieren sperren'});
cmd('adusers','Domänenbenutzer suchen',AD,'Get-ADUser','Benötigt das bereits vorhandene ActiveDirectory-Modul und Zugriff auf einen Domänencontroller.',[S('Filter','AD-Filter','*'),F('Properties','Zusätzliche Eigenschaften','list','DisplayName, Enabled, LastLogonDate'),S('SearchBase','Suchbasis (DN, optional)','',OPT)],{out:'Domaenenbenutzer',module:'ActiveDirectory',keywords:'ad domäne benutzer user active directory ldap suchen'});
cmd('adgroups','Domänengruppen suchen',AD,'Get-ADGroup','Liest Sicherheits- und Verteilergruppen aus Active Directory.',[S('Filter','AD-Filter','*'),S('SearchBase','Suchbasis (DN, optional)','',OPT)],{out:'Domaenengruppen',module:'ActiveDirectory',keywords:'ad domäne gruppe active directory'});
cmd('admembers','Domänengruppenmitglieder lesen',AD,'Get-ADGroupMember','Liest Mitglieder einer AD-Gruppe; optional auch verschachtelte Mitgliedschaften.',[S('Identity','Gruppe','Projektteam'),B('Recursive','Verschachtelte Gruppen auflösen')],{out:'ADMitglieder',module:'ActiveDirectory',keywords:'ad gruppe mitglieder verschachtelt domäne'});
cmd('adadd','Mitglied zur AD-Gruppe hinzufügen',AD,'Add-ADGroupMember','Fügt ein Konto zu einer vorhandenen AD-Gruppe hinzu.',[S('Identity','AD-Gruppe','Projektteam'),S('Members','Konto (sAMAccountName)','max')],{module:'ActiveDirectory',mutates:true,keywords:'ad domäne gruppe mitglied hinzufügen'});
cmd('adunlock','Domänenkonto entsperren',AD,'Unlock-ADAccount','Entsperrt ein gesperrtes AD-Konto.',[S('Identity','Konto','max')],{module:'ActiveDirectory',mutates:true,keywords:'ad konto entsperren locked benutzer'});
cmd('addisable','Domänenkonto deaktivieren',AD,'Disable-ADAccount','Deaktiviert ein AD-Konto.',[S('Identity','Konto','max')],{module:'ActiveDirectory',mutates:true,keywords:'ad konto deaktivieren sperren'});
cmd('adenable','Domänenkonto aktivieren',AD,'Enable-ADAccount','Aktiviert ein AD-Konto.',[S('Identity','Konto','max')],{module:'ActiveDirectory',mutates:true,keywords:'ad konto aktivieren'});
cmd('adcomputers','Domänencomputer suchen',AD,'Get-ADComputer','Liest Rechnerobjekte aus Active Directory.',[S('Filter','AD-Filter','*'),F('Properties','Eigenschaften','list','OperatingSystem, LastLogonDate')],{out:'Domaenencomputer',module:'ActiveDirectory',keywords:'ad computer rechner inventar domäne'});
cmd('adlocked','Gesperrte Domänenkonten suchen',AD,'Search-ADAccount','Liest gesperrte Benutzerkonten.',[B('LockedOut','Gesperrte Konten',true),B('UsersOnly','Nur Benutzer',true)],{out:'GesperrteKonten',module:'ActiveDirectory',keywords:'ad gesperrt locked konten benutzer finden'});
cmd('variable','Variable definieren',LOGIC,'$Variable = ...','Legt einen Wert für spätere Schritte fest. Der Wert ist ein PowerShell-Ausdruck.',[E('value','Wert als PowerShell-Ausdruck',"'C:\\Daten'")],{kind:'variable',out:'Quellordner',keywords:'variable wert parameter definieren pfad'});
cmd('foreach','Für jedes Element wiederholen',LOGIC,'foreach','Führt untergeordnete Schritte für jedes Objekt einer vorhandenen Variable aus.',[V('input','Liste / Datenvariable','Dateien'),V('item','Name des aktuellen Elements','Datei')],{kind:'foreach',uses:['input'],container:true,keywords:'schleife foreach jedes wiederholen massen batch'});
cmd('if','Bedingung',LOGIC,'if','Führt untergeordnete Schritte aus, wenn der Ausdruck True ergibt.',[E('condition','Bedingung',"Test-Path -LiteralPath 'C:\\Daten'")],{kind:'if',container:true,keywords:'wenn bedingung if prüfen existiert'});
cmd('try','Fehler behandeln',LOGIC,'try / catch','Führt untergeordnete Schritte aus; catch meldet einen Fehler und wirft ihn erneut.',[],{kind:'try',container:true,keywords:'fehlerbehandlung try catch exception robust'});
cmd('function','Eigene Funktion definieren',LOGIC,'function','Definiert eine wiederverwendbare Funktion mit optionalen Parametern.',[S('name','Funktionsname','Get-Projektbericht'),E('params','Parameterdeklarationen','',OPT)],{kind:'function',container:true,keywords:'funktion function wiederverwenden parameter'});
cmd('message','Meldung ausgeben',LOGIC,'Write-Host','Schreibt eine verständliche Fortschrittsmeldung in die Konsole.',[S('Object','Meldung','Schritt abgeschlossen')],{keywords:'meldung ausgabe schreiben status fortschritt'});
cmd('sleep','Warten',LOGIC,'Start-Sleep','Pausiert die Skriptausführung für eine feste Zeit.',[N('Seconds','Sekunden',2,{min:0,max:86400})],{keywords:'warten pause sleep verzögerung'});
cmd('custom','Eigener PowerShell-Code',LOGIC,'Eigener Code','Erweitert das Skript mit beliebigem PowerShell-Code. Eigene Befehle und Ausdrücke bleiben sichtbar.',[E('code','PowerShell-Code',"Get-Date"),C('effect','Wirkung',['Nur lesen','Änderung'],'Nur lesen')],{kind:'custom',keywords:'frei code befehl eigene skript alles editor erweitern'});

cmd('lines','Bestimmte Zeilen aus Dateien extrahieren',T,'Get-Content / Zeilenindex','Liest 1-basierte Zeilennummern aus vielen Textdateien und ergänzt den Quelldateinamen.',[S('folder','Suchordner','C:\\Daten'),S('filter','Dateimuster','*.txt'),S('lines','Zeilennummern (Komma getrennt)','4, 9'),C('encoding','Zeichenkodierung',['UTF8','Default','Unicode','ASCII'],'Default')],{kind:'lines',out:'Zeilendaten',keywords:'zeile zeilen vier neunte extrahieren txt dateien serienbrief nummer'});
cmd('localpassword','Kennwort eines lokalen Kontos ändern',U,'Set-LocalUser','Fragt das neue Kennwort erst bei der Skriptausführung verdeckt ab.',[S('Name','Benutzername','Max')],{kind:'localpassword',mutates:true,module:'Microsoft.PowerShell.LocalAccounts',keywords:'passwort kennwort reset benutzer lokal ändern'});
cmd('deletegroup','Lokale Gruppe entfernen',U,'Remove-LocalGroup','Entfernt eine lokale Gruppe; ihre Benutzerkonten bleiben erhalten.',[S('Name','Gruppenname','Projektteam')],{mutates:true,module:'Microsoft.PowerShell.LocalAccounts',risk:'Entfernt die lokale Gruppe und ihre Mitgliedschaften.',keywords:'gruppe löschen entfernen'});
cmd('delfreigabe','SMB-Freigabe entfernen',A,'Remove-SmbShare','Entfernt eine Freigabe. Der Ordnerinhalt wird nicht gelöscht.',[S('Name','Freigabename','Projekt')],{module:'SmbShare',mutates:true,keywords:'freigabe smb löschen entfernen'});
cmd('eventfilter','Ereignisse nach Zeitraum und Stufe suchen',SYS,'Get-WinEvent -FilterHashtable','Filtert direkt bei der Abfrage nach Protokoll, Ereignisstufe und Alter.',[C('log','Protokoll',['System','Application','Security'],'System'),C('level','Stufe',['1','2','3','4'],'2'),N('days','Letzte Tage',7,{min:1,max:3650})],{kind:'eventfilter',out:'GefilterteEreignisse',keywords:'eventlog fehler warnungen ereignisse datum zeitraum'});
cmd('remoting','Code auf einem anderen Server ausführen',SYS,'Invoke-Command','Verwendet vorhandenes PowerShell-Remoting/WinRM im internen Netzwerk. Der Code läuft auf dem Zielrechner.',[S('ComputerName','Zielserver','server01'),E('ScriptBlock','PowerShell-Code auf dem Zielserver','Get-Service'),C('effect','Wirkung',['Nur lesen','Änderung'],'Nur lesen')],{kind:'remoting',out:'RemoteErgebnis',keywords:'remote remoting server winrm fernsteuerung invoke command'});
cmd('taskremove','Geplante Aufgabe entfernen',TASK,'Unregister-ScheduledTask','Entfernt die Definition einer geplanten Aufgabe.',[S('TaskName','Aufgabenname','PowerHelp-Backup')],{module:'ScheduledTasks',mutates:true,keywords:'task aufgabe löschen entfernen scheduler'});
cmd('adnewuser','Domänenbenutzer anlegen',AD,'New-ADUser','Erstellt ein AD-Konto; das Kennwort wird erst beim Ausführen verdeckt abgefragt.',[S('Name','Anzeigename','Max Beispiel'),S('SamAccountName','sAMAccountName','max'),S('UserPrincipalName','UPN','max@example.local'),S('Path','OU-Pfad (DN)','OU=Benutzer,DC=example,DC=local'),B('Enabled','Konto aktivieren',true)],{kind:'adnewuser',module:'ActiveDirectory',mutates:true,keywords:'ad benutzer erstellen konto neu domäne'});
cmd('adsetuser','Domänenbenutzer ändern',AD,'Set-ADUser','Ändert Beschreibung und Abteilung eines vorhandenen AD-Kontos.',[S('Identity','Konto','max'),S('Description','Beschreibung','Projektkonto'),S('Department','Abteilung','IT')],{module:'ActiveDirectory',mutates:true,keywords:'ad benutzer ändern abteilung beschreibung'});
cmd('adpassword','Domänenkennwort zurücksetzen',AD,'Set-ADAccountPassword','Fragt das neue Kennwort erst bei der Skriptausführung verdeckt ab.',[S('Identity','Konto','max')],{kind:'adpassword',module:'ActiveDirectory',mutates:true,keywords:'ad passwort kennwort reset zurücksetzen'});
cmd('adnewgroup','Domänengruppe anlegen',AD,'New-ADGroup','Erstellt eine AD-Gruppe in einer vorhandenen Organisationseinheit.',[S('Name','Gruppenname','Projektteam'),C('GroupScope','Gruppenbereich',['Global','DomainLocal','Universal'],'Global'),C('GroupCategory','Gruppentyp',['Security','Distribution'],'Security'),S('Path','OU-Pfad (DN)','OU=Gruppen,DC=example,DC=local')],{module:'ActiveDirectory',mutates:true,keywords:'ad gruppe neu anlegen domäne'});
cmd('adremovemember','Mitglied aus AD-Gruppe entfernen',AD,'Remove-ADGroupMember','Entfernt eine AD-Gruppenmitgliedschaft.',[S('Identity','Gruppe','Projektteam'),S('Members','Konto','max')],{module:'ActiveDirectory',mutates:true,keywords:'ad gruppe mitglied entfernen'});
cmd('adous','Organisationseinheiten auflisten',AD,'Get-ADOrganizationalUnit','Liest Organisationseinheiten und ihre Distinguished Names.',[S('Filter','AD-Filter','*')],{module:'ActiveDirectory',out:'Organisationseinheiten',keywords:'ad ou organisationseinheit dn domäne'});
cmd('admove','AD-Objekt in eine OU verschieben',AD,'Move-ADObject','Verschiebt ein Objekt anhand seines Distinguished Name in eine Ziel-OU.',[S('Identity','Objekt-DN','CN=Max Beispiel,OU=Alt,DC=example,DC=local'),S('TargetPath','Ziel-OU-DN','OU=Benutzer,DC=example,DC=local')],{module:'ActiveDirectory',mutates:true,keywords:'ad ou verschieben konto computer'});

const PH_BY_ID = Object.fromEntries(PH_COMMANDS.map(d=>[d.id,d]));
function step(def,values={},out,children=[]) { return {def,values,out,children}; }
const PH_TEMPLATES = [
 {id:'regex-report',title:'Daten aus Textdateien extrahieren',description:'Kundennummern mit Regex sammeln und mit Quelldatei als CSV exportieren.',keywords:'regex daten auslesen extrahieren kundennummer text txt report',steps:[step('mkdir',{Path:'C:\\Daten\\Export'}),step('regex',{},'Treffer'),step('csvout',{},null)]},
 {id:'old-files',title:'Alte Dateien finden und entfernen',description:'Findet Dateien älter als 90 Tage. Der Vorschau-Modus überspringt das Löschen.',keywords:'alte dateien löschen aufräumen bereinigen älter temp',steps:[step('files',{LiteralPath:'C:\\Temp',Filter:'*',Recurse:true},'Dateien'),step('where',{input:'Dateien',condition:'$_.LastWriteTime -lt (Get-Date).AddDays(-90)'},'AlteDateien'),step('foreach',{input:'AlteDateien',item:'Datei'},null,[step('remove',{LiteralPath:{expr:'$Datei.FullName'}})])]},
 {id:'backup',title:'Ordner mit Robocopy sichern',description:'Kopiert einen Ordner inklusive Unterordnern und prüft den Robocopy-Exitcode.',keywords:'backup sicherung kopieren robocopy unterordner daten',steps:[step('mkdir',{Path:'D:\\Backup'}),step('robocopy',{})]},
 {id:'file-report',title:'Dateibestand als CSV inventarisieren',description:'Dateiname, Pfad, Größe und Änderungsdatum ausgeben.',keywords:'dateiliste inventar dateibestand excel csv größe',steps:[step('files',{Filter:'*',Recurse:true},'Dateien'),step('select',{input:'Dateien'},'Bericht'),step('mkdir',{Path:'C:\\Daten\\Export'}),step('csvout',{input:'Bericht'})]},
 {id:'users-report',title:'Lokale Benutzer dokumentieren',description:'Konten mit Aktivstatus und Beschreibung als CSV speichern.',keywords:'benutzer report user konten dokumentieren csv',steps:[step('users',{},'Benutzer'),step('select',{input:'Benutzer',Property:'Name, Enabled, Description'},'Bericht'),step('mkdir',{Path:'C:\\Daten\\Export'}),step('csvout',{input:'Bericht'})]},
 {id:'new-account',title:'Benutzer und Gruppe anlegen',description:'Lokale Gruppe und Konto erstellen, dann die Mitgliedschaft zuweisen.',keywords:'benutzer gruppe neu anlegen konto passwort',steps:[step('newgroup',{}),step('newuser',{}),step('addmember',{})]},
 {id:'csv-users',title:'Benutzer aus CSV anlegen',description:'Importiert Name, FullName und Description. Das Kennwort wird je Konto verdeckt abgefragt.',keywords:'benutzer csv massenimport import konto batch',steps:[step('csvin',{},'Datensaetze'),step('foreach',{input:'Datensaetze',item:'Datensatz'},null,[step('newuser',{Name:{expr:'$Datensatz.Name'},FullName:{expr:'$Datensatz.FullName'},Description:{expr:'$Datensatz.Description'}})])]},
 {id:'share-project',title:'Projektordner und Freigabe einrichten',description:'Lokale Gruppe, Ordner, NTFS-Rechte und SMB-Freigabe zusammenstellen.',keywords:'projekt freigabe smb ntfs rechte berechtigungen ordner',steps:[step('newgroup',{}),step('mkdir',{Path:'C:\\Daten\\Projekt'}),step('grant',{path:'C:\\Daten\\Projekt'}),step('newshare',{})]},
 {id:'services-stopped',title:'Gestoppte automatische Dienste finden',description:'CIM-Dienstobjekte nach Starttyp und Status filtern.',keywords:'dienste gestoppt automatisch service prüfen diagnose',steps:[step('cim',{ClassName:'Win32_Service'},'Dienste'),step('where',{input:'Dienste',condition:"$_.StartMode -eq 'Auto' -and $_.State -ne 'Running'"},'GestoppteDienste'),step('table',{input:'GestoppteDienste',Property:'Name, DisplayName, State, StartMode'})]},
 {id:'disk-space',title:'Freien Speicherplatz dokumentieren',description:'Volumes mit Kapazität und freiem Speicher als CSV exportieren.',keywords:'platte voll frei laufwerk speicher disk volumen kapazität',steps:[step('volumes',{},'Volumes'),step('select',{input:'Volumes',Property:'DriveLetter, FileSystemLabel, Size, SizeRemaining'},'Bericht'),step('mkdir',{Path:'C:\\Daten\\Export'}),step('csvout',{input:'Bericht'})]},
 {id:'event-report',title:'Systemfehler aus Ereignisprotokoll lesen',description:'Die letzten 1000 Systemereignisse nach Fehlerstufe filtern und exportieren.',keywords:'eventlog fehler ereignisse protokoll system report',steps:[step('events',{MaxEvents:1000},'Ereignisse'),step('where',{input:'Ereignisse',condition:'$_.Level -eq 2'},'Fehler'),step('select',{input:'Fehler',Property:'TimeCreated, Id, ProviderName, Message'},'Bericht'),step('mkdir',{Path:'C:\\Daten\\Export'}),step('csvout',{input:'Bericht'})]},
 {id:'ad-disabled',title:'Deaktivierte Domänenkonten dokumentieren',description:'Benötigt das bereits vorhandene ActiveDirectory-Modul.',keywords:'ad deaktivierte benutzer konten domäne csv report',steps:[step('adusers',{Filter:'Enabled -eq $false'},'Domaenenbenutzer'),step('select',{input:'Domaenenbenutzer',Property:'SamAccountName, DisplayName, Enabled, LastLogonDate'},'Bericht'),step('mkdir',{Path:'C:\\Daten\\Export'}),step('csvout',{input:'Bericht'})]},
 {id:'tcp-test',title:'Server auf SMB-Erreichbarkeit prüfen',description:'Host und TCP-Port 445 prüfen. Beide Ergebnisse erscheinen als Variablen.',keywords:'server verbindung smb erreichbar netzwerk port ping diagnose',steps:[step('ping',{},'Erreichbar'),step('port',{},'Porttest'),step('table',{input:'Porttest',Property:'ComputerName, RemoteAddress, RemotePort, TcpTestSucceeded'})]},
 {id:'replace-files',title:'Text in Dateien mit Regex ersetzen',description:'Liest jede Datei, ersetzt Treffer und schreibt UTF-8 zurück.',keywords:'regex ersetzen text dateien bereinigen replace mehrere',steps:[step('files',{},'Dateien'),step('foreach',{input:'Dateien',item:'Datei'},null,[step('read',{LiteralPath:{expr:'$Datei.FullName'}},'Text'),step('replace',{},'BereinigterText'),step('write',{LiteralPath:{expr:'$Datei.FullName'},Value:{expr:'$BereinigterText'}})])]},
 {id:'schedule-backup',title:'Skript täglich planen',description:'Registriert ein vorhandenes Skript als tägliche Aufgabe für die interaktive Anmeldung.',keywords:'task aufgabe täglich zeitplan powershell automatisch',steps:[step('tasknew',{})]}
];
